### ISSUE TITLE
Add PostgreSQL schema support

### ISSUE THREAD

**Issue by eleleung** [mfwgenerics/koala#12]
Could we please add support to specify schemas on tables? Dynamic schema specification is not necessary

Thank you :)

**Comment by mfwgenerics** [comment]
This should be possible now in 0.0.9

```kotlin
MyTable: Table("mySchema", "myTable")
```
will produce queries like
```sql
SELECT * FROM "mySchema"."myTable"
```

**Comment by eleleung** [comment]
confirmed that this works for me!
