### ISSUE TITLE
Add jsonb type

### ISSUE THREAD

**Issue by eleleung** [mfwgenerics/koala#27]
I feel like I'm spamming a lot lol but would be nice to have support for Postgres' JSONB. Since we're not using Koala to manage the actual creation of the tables we just use `JSON` in the Koala table definitions while our Flyway definitions specify `JSONB`. 

It didn't appear too difficult to add (see branch I'm playing with [here](https://github.com/mfwgenerics/koala/compare/main...eleleung:koala:add-jsonb?expand=1) but I could be missing something. This implementation meant I had to add JSONB awareness into the MySQL schema diff logic which also seems not ideal.

**Comment by mfwgenerics** [comment]
Now available as `io.koalaql.postgres.ddl.JSONB`
